using AssetManager.Data;
using AssetManager.Helpers;
using AssetManager.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AssetManager.Controllers
{
    [Authorize]
    public class AssetsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<AssetsController> _logger;

        public AssetsController(ApplicationDbContext context, ILogger<AssetsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        /// <summary>
        /// VIEW ALL ASSETS - Accessible to all authenticated users
        /// Admin: See all with management options
        /// Approval: See all with approve-only options (cannot request)
        /// Issuer: See available and their assigned assets with request option
        /// Viewer: See all (view only)
        /// </summary>
        public async Task<IActionResult> Index()
        {
            var assets = await _context.Assets
                .Include(a => a.User)
                .AsNoTracking()
                .ToListAsync();
            return View(assets);
        }

        /// <summary>
        /// VIEW MY REQUESTS - Shows user's own asset requests
        /// </summary>
        public async Task<IActionResult> MyRequests()
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email) ?? string.Empty;
            var userId = int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out var uid) ? uid : 0;

            var requests = await _context.AssetRequests
                .Include(r => r.Asset)
                .Include(r => r.RequestedAssets)
                    .ThenInclude(ri => ri.Asset)
                .Where(r => r.UserId == userId || r.RequestedBy == userEmail)
                .OrderByDescending(r => r.RequestDate)
                .ToListAsync();

            return View(requests);
        }

        /// <summary>
        /// VIEW ASSET DETAILS - Accessible to all authenticated users
        /// Shows a non-editable view of asset information
        /// </summary>
        public async Task<IActionResult> Details(int id)
        {
            var asset = await _context.Assets.FindAsync(id);
            if (asset == null)
                return NotFound();

            return View(asset);
        }

        /// <summary>
        /// CREATE ASSET - Admin Only
        /// Only IT/System Administrators can create new assets in inventory
        /// </summary>
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AssetTag,Category,Brand,Model,SerialNumber,PurchaseDate,PurchasePrice,Location,Notes")] Asset asset)
        {
            // RowVersion is auto-generated by the database on insert — it is never posted from the form.
            // Remove it from ModelState so its absence does not silently block the Create action.
            ModelState.Remove(nameof(Asset.RowVersion));

            if (!ModelState.IsValid)
                return View(asset);

            asset.Status = AssetStatus.Ready;
            asset.AssignedDate = null;
            asset.AssignedTo = null;
            asset.UserId = null;

            _context.Assets.Add(asset);
            await _context.SaveChangesAsync();

            TempData["Success"] = "Asset created successfully!";
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// EDIT ASSET - Admin Only
        /// Only IT/System Administrators can modify asset details
        /// </summary>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var asset = await _context.Assets.FindAsync(id);
            if (asset == null)
                return NotFound();

            // Load all active users for the AssignedTo dropdown
            var users = await _context.Users
                .Where(u => u.IsActive)
                .OrderBy(u => u.Email)
                .ToListAsync();

            ViewBag.Users = users;

            return View(asset);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Asset asset)
        {
            if (id != asset.Id)
                return NotFound();

            // RowVersion is never posted in the Edit form — remove it from ModelState
            // to prevent it from silently blocking saves.
            ModelState.Remove(nameof(Asset.RowVersion));

            if (!ModelState.IsValid)
            {
                // Reload users if validation fails
                var users = await _context.Users
                    .Where(u => u.IsActive)
                    .OrderBy(u => u.Email)
                    .ToListAsync();

                ViewBag.Users = users;
                return View(asset);
            }

            try
            {
                // Validate that admin is only setting allowed statuses
                var allowedStatuses = new[] { AssetStatus.Ready, AssetStatus.Maintenance, AssetStatus.Retired };
                if (!allowedStatuses.Contains(asset.Status))
                {
                    ModelState.AddModelError("Status", "Invalid status selection. Only Ready, Maintenance, and Retired are allowed.");
                    var users = await _context.Users.Where(u => u.IsActive).OrderBy(u => u.Email).ToListAsync();
                    ViewBag.Users = users;
                    return View(asset);
                }

                // Retrieve existing entity from database to prevent over-posting
                var existingAsset = await _context.Assets.FindAsync(id);
                if (existingAsset == null)
                    return NotFound();

                // Update only intended properties
                existingAsset.AssetTag = asset.AssetTag;
                existingAsset.Category = asset.Category;
                existingAsset.Brand = asset.Brand;
                existingAsset.Model = asset.Model;
                existingAsset.SerialNumber = asset.SerialNumber;
                existingAsset.Status = asset.Status;
                existingAsset.Location = asset.Location;
                existingAsset.PurchaseDate = asset.PurchaseDate;
                existingAsset.PurchasePrice = asset.PurchasePrice;
                existingAsset.AssignedTo = asset.AssignedTo;
                existingAsset.AssignedDate = asset.AssignedDate;
                existingAsset.Notes = asset.Notes;

                // Update UserId based on AssignedTo email
                if (!string.IsNullOrEmpty(existingAsset.AssignedTo))
                {
                    var assignedUser = await _context.Users
                        .FirstOrDefaultAsync(u => u.Email == existingAsset.AssignedTo && u.IsActive);
                    if (assignedUser == null)
                    {
                        ModelState.AddModelError("AssignedTo", "No active user found with this email address.");
                        var users = await _context.Users.Where(u => u.IsActive).OrderBy(u => u.Email).ToListAsync();
                        ViewBag.Users = users;
                        return View(asset);
                    }
                    existingAsset.UserId = assignedUser.Id;
                }
                else
                {
                    existingAsset.UserId = null;
                }

                // Cancel any pending requests when admin changes status to Ready, Maintenance, or Retired
                if (existingAsset.Status == AssetStatus.Ready || existingAsset.Status == AssetStatus.Maintenance || existingAsset.Status == AssetStatus.Retired)
                {
                    // Clear assignment fields — asset is no longer assigned to anyone
                    existingAsset.AssignedTo = null;
                    existingAsset.AssignedDate = null;
                    existingAsset.UserId = null;

                    var adminEmail = User.FindFirstValue(ClaimTypes.Email) ?? "Admin";
                    var cancelNote = $" - Cancelled by admin when asset status changed to {existingAsset.Status}";

                    // Cancel legacy single-asset pending requests
                    var pendingRequests = await _context.AssetRequests
                        .Where(r => r.AssetId == id && r.Status == RequestStatuses.Pending)
                        .ToListAsync();

                    foreach (var request in pendingRequests)
                    {
                        request.Status = RequestStatuses.Cancelled;
                        request.ApprovedBy = adminEmail;
                        request.ApprovalDate = DateTime.UtcNow;
                        request.Notes = request.Notes.AppendNote(cancelNote);
                    }

                    // Cancel multi-asset pending requests that include this asset
                    var pendingMultiRequests = await _context.AssetRequestItems
                        .Include(ri => ri.AssetRequest)
                        .Where(ri => ri.AssetId == id && ri.AssetRequest != null && ri.AssetRequest.Status == RequestStatuses.Pending)
                        .Select(ri => ri.AssetRequest!)
                        .Distinct()
                        .ToListAsync();

                    foreach (var request in pendingMultiRequests)
                    {
                        request.Status = RequestStatuses.Cancelled;
                        request.ApprovedBy = adminEmail;
                        request.ApprovalDate = DateTime.UtcNow;
                        request.Notes = request.Notes.AppendNote(cancelNote);
                    }
                }

                await _context.SaveChangesAsync();
                TempData["Success"] = "Asset updated successfully!";
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (! await AssetExists(asset.Id))
                    return NotFound();
                throw;
            }
        }

        /// <summary>
        /// DELETE ASSET - Admin Only
        /// Only IT/System Administrators can remove assets from inventory
        /// </summary>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var asset = await _context.Assets.FindAsync(id);
            if (asset == null)
                return NotFound();

            // Check if asset is currently assigned
            if (asset.Status == AssetStatus.Assigned)
            {
                TempData["Error"] = "Cannot delete an asset that is currently assigned. Please return it first.";
                return RedirectToAction(nameof(Index));
            }

            // Check if asset has pending requests (old single-asset requests)
            var hasPendingRequests = await _context.AssetRequests
                .AnyAsync(r => r.AssetId == id && r.Status == RequestStatuses.Pending);

            if (hasPendingRequests)
            {
                TempData["Error"] = "Cannot delete an asset with pending requests. Please resolve them first.";
                return RedirectToAction(nameof(Index));
            }

            // Check for pending items in multi-asset requests
            var hasPendingRequestItems = await _context.AssetRequestItems
                .Include(ri => ri.AssetRequest)
                .AnyAsync(ri => ri.AssetId == id && ri.AssetRequest != null && ri.AssetRequest.Status == RequestStatuses.Pending);

            if (hasPendingRequestItems)
            {
                TempData["Error"] = "Cannot delete an asset with pending requests. Please resolve them first.";
                return RedirectToAction(nameof(Index));
            }

            return View(asset);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asset = await _context.Assets.FindAsync(id);
            if (asset == null)
                return NotFound();

            var assetTag = asset.AssetTag ?? "Unknown";

            using var transaction = await _context.Database.BeginTransactionAsync();
            try
            {
                // Re-check constraints inside the transaction to close the race window
                if (asset.Status == AssetStatus.Assigned)
                {
                    TempData["Error"] = "Cannot delete an assigned asset. Please return it first.";
                    return RedirectToAction(nameof(Index));
                }

                var hasPendingRequests = await _context.AssetRequests
                    .AnyAsync(r => r.AssetId == id && r.Status == RequestStatuses.Pending);

                if (hasPendingRequests)
                {
                    TempData["Error"] = "Cannot delete an asset with pending requests. Please resolve them first.";
                    return RedirectToAction(nameof(Index));
                }

                var hasPendingRequestItems = await _context.AssetRequestItems
                    .Include(ri => ri.AssetRequest)
                    .AnyAsync(ri => ri.AssetId == id && ri.AssetRequest != null && ri.AssetRequest.Status == RequestStatuses.Pending);

                if (hasPendingRequestItems)
                {
                    TempData["Error"] = "Cannot delete an asset with pending requests. Please resolve them first.";
                    return RedirectToAction(nameof(Index));
                }

                var requestItems = await _context.AssetRequestItems.Where(ri => ri.AssetId == id).ToListAsync();
                _context.AssetRequestItems.RemoveRange(requestItems);

                var assetRequests = await _context.AssetRequests.Where(r => r.AssetId == id).ToListAsync();
                foreach (var request in assetRequests)
                {
                    request.AssetId = null;
                }

                _context.Assets.Remove(asset);
                await _context.SaveChangesAsync();
                await transaction.CommitAsync();

                TempData["Success"] = $"Asset {assetTag} deleted successfully!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                _logger.LogError(ex, "Failed to delete asset {AssetId}", id);
                TempData["Error"] = "Failed to delete asset. Please try again.";
                return RedirectToAction(nameof(Index));
            }
        }

        /// <summary>
        /// REQUEST ASSET(S) - Issuer Only (GET - Show form for single or multiple assets)
        /// Allows requesting one or multiple assets in a single request
        /// </summary>
        [HttpGet]
        [Authorize(Roles = "Issuer")]
        public async Task<IActionResult> RequestAsset(int? id)
        {
            if (id.HasValue)
            {
                // Single-asset path: scope AvailableAssets to just this one asset
                // so the view renders the pre-selected card instead of the checkbox list
                var asset = await _context.Assets.FindAsync(id.Value);
                if (asset == null)
                    return NotFound();

                if (asset.Status != AssetStatus.Ready)
                {
                    TempData["Error"] = "This asset is not available for request.";
                    return RedirectToAction(nameof(Index));
                }

                ViewBag.SingleAssetId = id.Value;
                ViewBag.AvailableAssets = new List<Asset> { asset };
            }
            else
            {
                // Multi-asset path: load all available assets
                ViewBag.AvailableAssets = await _context.Assets
                    .Where(a => a.Status == AssetStatus.Ready)
                    .OrderBy(a => a.AssetTag)
                    .ToListAsync();
            }

            return View();
        }

        /// <summary>
        /// REQUEST ASSET(S) - Issuer Only (POST - Submit request for one or multiple assets)
        /// Creates a single request that can contain multiple assets
        /// </summary>
        [HttpPost]
        [Authorize(Roles = "Issuer")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RequestAssetConfirmed(List<int> assetIds, string justification, DateTime? expectedReturnDate)
        {
            // Validate inputs
            if (assetIds == null || !assetIds.Any())
            {
                ModelState.AddModelError("AssetIds", "Please select at least one asset.");
                ViewBag.AvailableAssets = await _context.Assets
                    .Where(a => a.Status == AssetStatus.Ready)
                    .OrderBy(a => a.AssetTag)
                    .ToListAsync();
                return View("RequestAsset");
            }

            if (string.IsNullOrWhiteSpace(justification))
            {
                ModelState.AddModelError("Justification", "Justification is required.");
                ViewBag.AvailableAssets = await _context.Assets
                    .Where(a => a.Status == AssetStatus.Ready)
                    .OrderBy(a => a.AssetTag)
                    .ToListAsync();
                return View("RequestAsset");
            }

            if (!expectedReturnDate.HasValue || expectedReturnDate.Value.Date <= DateTime.UtcNow.Date)
            {
                ModelState.AddModelError("ExpectedReturnDate", "Expected return date must be a future date.");
                ViewBag.AvailableAssets = await _context.Assets
                    .Where(a => a.Status == AssetStatus.Ready)
                    .OrderBy(a => a.AssetTag)
                    .ToListAsync();
                return View("RequestAsset");
            }

            // Get current user info
            var userId = int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out var uid) ? uid : 0;
            var userEmail = User.FindFirstValue(ClaimTypes.Email) ?? "Unknown";

            // Load requested assets and verify they're all available
            var assets = await _context.Assets
                .Where(a => assetIds.Contains(a.Id))
                .ToListAsync();

            if (assets.Count != assetIds.Count)
            {
                TempData["Error"] = "One or more selected assets could not be found.";
                return RedirectToAction(nameof(Index));
            }

            var unavailableAssets = assets.Where(a => a.Status != AssetStatus.Ready).ToList();
            if (unavailableAssets.Any())
            {
                TempData["Error"] = $"The following assets are not available: {string.Join(", ", unavailableAssets.Select(a => a.AssetTag))}";
                return RedirectToAction(nameof(Index));
            }

            using var transaction = await _context.Database.BeginTransactionAsync();
            try
            {
                // Create the parent request (one request for multiple assets)
                var request = new AssetRequest
                {
                    UserId = userId,
                    RequestedBy = userEmail,
                    RequestType = RequestTypes.Request,
                    Status = RequestStatuses.Pending,
                    RequestDate = DateTime.UtcNow,
                    ExpectedReturnDate = expectedReturnDate.Value,
                    Justification = justification.Trim(),
                    Notes = $"Request submitted by {userEmail} for {assets.Count} asset(s)"
                };

                _context.AssetRequests.Add(request);
                await _context.SaveChangesAsync(); // Save to get the request ID

                // Create request items for each asset
                foreach (var asset in assets)
                {
                    var requestItem = new AssetRequestItem
                    {
                        AssetRequestId = request.Id,
                        AssetId = asset.Id
                    };
                    _context.AssetRequestItems.Add(requestItem);

                    // Update asset status to Pending
                    asset.Status = AssetStatus.Pending;
                    _context.Assets.Update(asset);
                }

                await _context.SaveChangesAsync();
                await transaction.CommitAsync();

                TempData["Success"] = $"Request for {assets.Count} asset(s) submitted successfully! Waiting for approval.";
                return RedirectToAction(nameof(MyRequests));
            }
            catch (DbUpdateConcurrencyException)
            {
                await transaction.RollbackAsync();
                TempData["Error"] = "One or more assets were just reserved by someone else. Please re-select.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                _logger.LogError(ex, "Failed to submit asset request for user {UserId}", userId);
                TempData["Error"] = "Failed to submit request. Please try again or contact support.";
                return RedirectToAction(nameof(Index));
            }
        }

        /// <summary>
        /// RETURN ASSET - Issuer Only
        /// Issuers can return ANY assigned asset back to inventory
        /// Admins can change asset status directly via Edit
        /// </summary>
        [HttpGet]
        [Authorize(Roles = "Issuer")]
        public async Task<IActionResult> ReturnAsset(int id)
        {
            var asset = await _context.Assets.FindAsync(id);

            if (asset == null)
                return NotFound();

            if (asset.Status != AssetStatus.Assigned)
            {
                TempData["Error"] = "Only assigned assets can be returned.";
                return RedirectToAction(nameof(Index));
            }

            return View(asset);
        }

        [HttpPost, ActionName("ReturnAsset")]
        [Authorize(Roles = "Issuer")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReturnAssetConfirmed(int id)
        {
            var asset = await _context.Assets.FindAsync(id);

            if (asset == null)
                return NotFound();

            if (asset.Status != AssetStatus.Assigned)
            {
                TempData["Error"] = "Only assigned assets can be returned.";
                return RedirectToAction(nameof(Index));
            }

            var currentUserId = int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out var uid) ? uid : 0;
            var currentUserEmail = User.FindFirstValue(ClaimTypes.Email);
            var previousAssignee = asset.AssignedTo;

            var returnRequest = new AssetRequest
            {
                AssetId = id,
                UserId = currentUserId,
                RequestedBy = currentUserEmail ?? "Unknown",
                RequestType = RequestTypes.Return,
                Status = RequestStatuses.Approved,
                RequestDate = DateTime.UtcNow,
                ApprovalDate = DateTime.UtcNow,
                ApprovedBy = currentUserEmail ?? "Unknown",
                Notes = $"Asset returned from {asset.AssignedTo} by {currentUserEmail ?? "Unknown"}"
            };

            asset.Status = AssetStatus.Ready;
            asset.AssignedTo = null;
            asset.AssignedDate = null;
            asset.UserId = null;

            using var transaction = await _context.Database.BeginTransactionAsync();
            try
            {
                _context.AssetRequests.Add(returnRequest);
                _context.Assets.Update(asset);
                await _context.SaveChangesAsync();
                await transaction.CommitAsync();

                TempData["Success"] = $"Asset returned successfully from {previousAssignee ?? "Unknown"} and is now available.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                _logger.LogError(ex, "Failed to return asset {AssetId}", id);
                TempData["Error"] = "Failed to return asset. Please try again.";
                return RedirectToAction(nameof(Index));
            }
        }

        /// <summary>
        /// RETURN MULTIPLE ASSETS - Issuer Only (GET)
        /// Show form to select multiple assigned assets for return
        /// </summary>
        [HttpGet]
        [Authorize(Roles = "Issuer")]
        public async Task<IActionResult> ReturnMultipleAssets()
        {
            // Load all assigned assets
            ViewBag.AssignedAssets = await _context.Assets
                .Where(a => a.Status == AssetStatus.Assigned)
                .OrderBy(a => a.AssignedTo)
                .ThenBy(a => a.AssetTag)
                .ToListAsync();

            return View();
        }

        /// <summary>
        /// RETURN MULTIPLE ASSETS - Issuer Only (POST)
        /// Process the return of multiple assets
        /// </summary>
        [HttpPost]
        [Authorize(Roles = "Issuer")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReturnMultipleAssetsConfirmed(List<int> assetIds, string? returnNotes)
        {
            if (assetIds == null || !assetIds.Any())
            {
                TempData["Error"] = "Please select at least one asset to return.";
                return RedirectToAction(nameof(ReturnMultipleAssets));
            }

            // Get current user info
            var currentUserId = int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out var uid) ? uid : 0;
            var currentUserEmail = User.FindFirstValue(ClaimTypes.Email);

            // Load the assets
            var assets = await _context.Assets
                .Where(a => assetIds.Contains(a.Id))
                .ToListAsync();

            if (assets.Count != assetIds.Count)
            {
                TempData["Error"] = "One or more selected assets could not be found.";
                return RedirectToAction(nameof(ReturnMultipleAssets));
            }

            // Verify all are assigned
            var notAssignedAssets = assets.Where(a => a.Status != AssetStatus.Assigned).ToList();
            if (notAssignedAssets.Any())
            {
                TempData["Error"] = $"The following assets are not assigned: {string.Join(", ", notAssignedAssets.Select(a => a.AssetTag))}";
                return RedirectToAction(nameof(ReturnMultipleAssets));
            }

            using var transaction = await _context.Database.BeginTransactionAsync();
            try
            {
                // Create a single return request for all assets
                var returnRequest = new AssetRequest
                {
                    UserId = currentUserId,
                    RequestedBy = currentUserEmail ?? "Unknown",
                    RequestType = RequestTypes.Return,
                    Status = RequestStatuses.Approved, // Auto-approve returns
                    RequestDate = DateTime.UtcNow,
                    ApprovalDate = DateTime.UtcNow,
                    ApprovedBy = currentUserEmail ?? "Unknown",
                    Notes = $"Bulk return of {assets.Count} asset(s) by {currentUserEmail ?? "Unknown"}" +
                            (string.IsNullOrWhiteSpace(returnNotes) ? "" : $"\nNotes: {returnNotes}")
                };

                _context.AssetRequests.Add(returnRequest);
                await _context.SaveChangesAsync(); // Save to get the request ID

                // Create request items and update each asset
                var assigneesList = new List<string>();
                foreach (var asset in assets)
                {
                    var requestItem = new AssetRequestItem
                    {
                        AssetRequestId = returnRequest.Id,
                        AssetId = asset.Id
                    };
                    _context.AssetRequestItems.Add(requestItem);

                    // Track who had the asset
                    if (!string.IsNullOrEmpty(asset.AssignedTo) && !assigneesList.Contains(asset.AssignedTo))
                    {
                        assigneesList.Add(asset.AssignedTo);
                    }

                    // Update asset status
                    asset.Status = AssetStatus.Ready;
                    asset.AssignedTo = null;
                    asset.AssignedDate = null;
                    asset.UserId = null;
                    _context.Assets.Update(asset);
                }

                await _context.SaveChangesAsync();
                await transaction.CommitAsync();

                var assigneesText = assigneesList.Any()
                    ? $" from {string.Join(", ", assigneesList)}"
                    : "";

                TempData["Success"] = $"Successfully returned {assets.Count} asset(s){assigneesText}. All assets are now available.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                _logger.LogError(ex, "Failed to bulk return assets for user {UserId}", currentUserId);
                TempData["Error"] = "Failed to return assets. Please try again or contact support.";
                return RedirectToAction(nameof(ReturnMultipleAssets));
            }
        }

        /// <summary>
        /// GENERATE QR CODE - Generates QR code image for an asset
        /// Returns a PNG image of the QR code
        /// </summary>
        [Authorize]
        public async Task<IActionResult> GenerateQRCode(int id)
        {
            var asset = await _context.Assets.FindAsync(id);
            if (asset == null)
                return NotFound();

            // Generate the URL that the QR code will point to
            var baseUrl = $"{Request.Scheme}://{Request.Host}";
            var qrUrl = asset.GetQRCodeUrl(baseUrl);

            // Generate QR code as byte array
            byte[] qrCodeBytes = QRCodeHelper.GenerateQRCodeBytes(qrUrl, 10);

            return File(qrCodeBytes, "image/png");
        }

        /// <summary>
        /// VIEW ASSET BY QR CODE - Public endpoint that requires login
        /// This is where users are directed when scanning a QR code
        /// Requires authentication but accessible to all logged-in users
        /// </summary>
        [Authorize]
        public async Task<IActionResult> ViewByQR(int id)
        {
            var asset = await _context.Assets
                .Include(a => a.User)
                .FirstOrDefaultAsync(a => a.Id == id);

            if (asset == null)
            {
                TempData["Error"] = "Asset not found.";
                return RedirectToAction(nameof(Index));
            }

            // Store a message to indicate this was accessed via QR code
            ViewBag.AccessedViaQR = true;

            return View("Details", asset);
        }

        /// <summary>
        /// DOWNLOAD QR CODE - Downloads the QR code as a PNG file
        /// </summary>
        [Authorize]
        public async Task<IActionResult> DownloadQRCode(int id)
        {
            var asset = await _context.Assets.FindAsync(id);
            if (asset == null)
                return NotFound();

            // Generate the URL that the QR code will point to
            var baseUrl = $"{Request.Scheme}://{Request.Host}";
            var qrUrl = asset.GetQRCodeUrl(baseUrl);

            // Generate QR code as byte array with higher resolution for printing
            byte[] qrCodeBytes = QRCodeHelper.GenerateQRCodeBytes(qrUrl, 20);

            // Clean the asset tag for use in filename
            var safeAssetTag = (asset.AssetTag ?? "Unknown").Replace(" ", "_").Replace("/", "-");
            var fileName = $"QR_{safeAssetTag}.png";

            return File(qrCodeBytes, "image/png", fileName);
        }

        /// <summary>
        /// Helper method to check if asset exists
        /// </summary>
        private async Task<bool> AssetExists(int id)
        {
            return await _context.Assets.AnyAsync(e => e.Id == id);
        }
    }
}
